// <auto-generated />
using System;
using AKD.AKDTrading.Services.Finance.API.DomainModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PUCARS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PucarsServices.Models.BoardMeeting", b =>
                {
                    b.Property<uint>("BoardMeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AccountsEnded")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ClosedForm")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ClosedTo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("HeldDate")
                        .HasColumnType("date");

                    b.Property<string>("HeldPalce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("HeldTime")
                        .HasColumnType("time(6)");

                    b.Property<DateOnly>("PeriodEnded")
                        .HasColumnType("date");

                    b.HasKey("BoardMeetingId");

                    b.ToTable("boardMeetings");
                });
#pragma warning restore 612, 618
        }
    }
}
